.MODEL SMALL
.STACK 100H

.CODE MAIN


MAIN PROC  
    
    JMP IN  ;LEVEL IN FOR INPUT lEVEL
    
    IN:
    MOV AH,1 ;CALL INPUT FUNCTION
    INT 21H  ;EXECUTE TILL PREVIOUS
    
    MOV BL,AL ;INPUT CHAR STORED IN AL, SO NEEDS TO STORE ANOTHER LOCATION
    JMP PR  ;JUMP TO PRINT
     
     
    PR:
    MOV AH,2  ;CALL DISPLAY FUNCTION
    MOV DL,'A'  ;DISPLAY CHAR 'A'
    INT 21H    ;EXECUTE TILL PREVIOUS
    JMP OUT 
      
    OUT:
    ;FOR GOINT NEXT LINE 0DH+OAH  
    MOV DL,0DH
    INT 21H     ;EXECUTE TILL PREVIOUS
    MOV DL,0AH
    INT 21H    ;EXECUTE TILL PREVIOUS
    
    MOV DL,BL
    INT 21H
    
    JMP EXIT ; JUMP TO EXIT
     
    EXIT:
    MOV AH,4CH  ;4CH TO RETURN TO SYSTEM
    INT 21H
    
    MAIN ENDP   ; END PROCEDURE

END MAIN
